[package]
name = "rendimentos"
version = "0.1.0"
authors = ["Raimundo Martins <code@raimundo.space>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "*"
derive_builder = "*"
